### ISSUE TITLE
Spruce up website

### ISSUE THREAD

**Issue by i-daszkowski** [plberg/cs373-idb#47] opened 2015-04-01 20:57 UTC
Make the website look better and add some more embedded media to each of the model pages (i.e. Twitter feeds, Facebook page, etc).

**Comment by jabrouwer82** [comment] 2015-04-07 19:49
Duplicate of #53 #56 #32 #31 etc

**Comment by jabrouwer82** [comment] 2015-04-07 19:49
Duplicate of #53 #56 #32 #31

**Closed as completed by jabrouwer82** 2015-04-07 19:49 UTC
Labels: duplicate
